name: my_mobx_project  # Renomeie para algo diferente de 'mobx'
description: "A new Flutter project using MobX for state management."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_mobx: ^2.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  mobx_codegen: ^2.0.0
  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
